name: Publish to npm

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      
      - name: Install dependencies and build
        run: pnpm install --frozen-lockfile && pnpm build
      
      - name: Publish to npm on tag or release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 